// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.21.12
// source: faucetETH/faucetETH.proto

package faucetETH

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	FaucetETH_RequestETH_FullMethodName = "/faucetETH.FaucetETH/RequestETH"
)

// FaucetETHClient is the client API for FaucetETH service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FaucetETHClient interface {
	RequestETH(ctx context.Context, in *FaucetETHRequest, opts ...grpc.CallOption) (*FaucetETHResponse, error)
}

type faucetETHClient struct {
	cc grpc.ClientConnInterface
}

func NewFaucetETHClient(cc grpc.ClientConnInterface) FaucetETHClient {
	return &faucetETHClient{cc}
}

func (c *faucetETHClient) RequestETH(ctx context.Context, in *FaucetETHRequest, opts ...grpc.CallOption) (*FaucetETHResponse, error) {
	out := new(FaucetETHResponse)
	err := c.cc.Invoke(ctx, FaucetETH_RequestETH_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FaucetETHServer is the server API for FaucetETH service.
// All implementations must embed UnimplementedFaucetETHServer
// for forward compatibility
type FaucetETHServer interface {
	RequestETH(context.Context, *FaucetETHRequest) (*FaucetETHResponse, error)
	mustEmbedUnimplementedFaucetETHServer()
}

// UnimplementedFaucetETHServer must be embedded to have forward compatible implementations.
type UnimplementedFaucetETHServer struct {
}

func (UnimplementedFaucetETHServer) RequestETH(context.Context, *FaucetETHRequest) (*FaucetETHResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestETH not implemented")
}
func (UnimplementedFaucetETHServer) mustEmbedUnimplementedFaucetETHServer() {}

// UnsafeFaucetETHServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FaucetETHServer will
// result in compilation errors.
type UnsafeFaucetETHServer interface {
	mustEmbedUnimplementedFaucetETHServer()
}

func RegisterFaucetETHServer(s grpc.ServiceRegistrar, srv FaucetETHServer) {
	s.RegisterService(&FaucetETH_ServiceDesc, srv)
}

func _FaucetETH_RequestETH_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FaucetETHRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FaucetETHServer).RequestETH(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FaucetETH_RequestETH_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FaucetETHServer).RequestETH(ctx, req.(*FaucetETHRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FaucetETH_ServiceDesc is the grpc.ServiceDesc for FaucetETH service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FaucetETH_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "faucetETH.FaucetETH",
	HandlerType: (*FaucetETHServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RequestETH",
			Handler:    _FaucetETH_RequestETH_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "faucetETH/faucetETH.proto",
}
