// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.21.12
// source: faucet/faucet.proto

package faucet

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FaucetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletAddress string `protobuf:"bytes,1,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
}

func (x *FaucetRequest) Reset() {
	*x = FaucetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faucet_faucet_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaucetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaucetRequest) ProtoMessage() {}

func (x *FaucetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_faucet_faucet_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaucetRequest.ProtoReflect.Descriptor instead.
func (*FaucetRequest) Descriptor() ([]byte, []int) {
	return file_faucet_faucet_proto_rawDescGZIP(), []int{0}
}

func (x *FaucetRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

type FaucetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EthTransactionHash   string `protobuf:"bytes,1,opt,name=eth_transaction_hash,json=ethTransactionHash,proto3" json:"eth_transaction_hash,omitempty"`
	TokenTransactionHash string `protobuf:"bytes,2,opt,name=token_transaction_hash,json=tokenTransactionHash,proto3" json:"token_transaction_hash,omitempty"`
	EthBalance           string `protobuf:"bytes,3,opt,name=eth_balance,json=ethBalance,proto3" json:"eth_balance,omitempty"`
	TokenBalance         string `protobuf:"bytes,4,opt,name=token_balance,json=tokenBalance,proto3" json:"token_balance,omitempty"`
}

func (x *FaucetResponse) Reset() {
	*x = FaucetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_faucet_faucet_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FaucetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FaucetResponse) ProtoMessage() {}

func (x *FaucetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_faucet_faucet_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FaucetResponse.ProtoReflect.Descriptor instead.
func (*FaucetResponse) Descriptor() ([]byte, []int) {
	return file_faucet_faucet_proto_rawDescGZIP(), []int{1}
}

func (x *FaucetResponse) GetEthTransactionHash() string {
	if x != nil {
		return x.EthTransactionHash
	}
	return ""
}

func (x *FaucetResponse) GetTokenTransactionHash() string {
	if x != nil {
		return x.TokenTransactionHash
	}
	return ""
}

func (x *FaucetResponse) GetEthBalance() string {
	if x != nil {
		return x.EthBalance
	}
	return ""
}

func (x *FaucetResponse) GetTokenBalance() string {
	if x != nil {
		return x.TokenBalance
	}
	return ""
}

var File_faucet_faucet_proto protoreflect.FileDescriptor

var file_faucet_faucet_proto_rawDesc = []byte{
	0x0a, 0x13, 0x66, 0x61, 0x75, 0x63, 0x65, 0x74, 0x2f, 0x66, 0x61, 0x75, 0x63, 0x65, 0x74, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x66, 0x61, 0x75, 0x63, 0x65, 0x74, 0x1a, 0x1c, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x36, 0x0a, 0x0d, 0x66,
	0x61, 0x75, 0x63, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e,
	0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x5f, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0xbe, 0x01, 0x0a, 0x0e, 0x66, 0x61, 0x75, 0x63, 0x65, 0x74, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x65, 0x74, 0x68, 0x5f, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x65, 0x74, 0x68, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x34, 0x0a, 0x16, 0x74, 0x6f, 0x6b, 0x65,
	0x6e, 0x5f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x68, 0x61,
	0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1f,
	0x0a, 0x0b, 0x65, 0x74, 0x68, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x65, 0x74, 0x68, 0x42, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65, 0x12,
	0x23, 0x0a, 0x0d, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x62, 0x61, 0x6c, 0x61, 0x6e, 0x63, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x61, 0x6c,
	0x61, 0x6e, 0x63, 0x65, 0x32, 0x5e, 0x0a, 0x06, 0x66, 0x61, 0x75, 0x63, 0x65, 0x74, 0x12, 0x54,
	0x0a, 0x07, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x15, 0x2e, 0x66, 0x61, 0x75, 0x63,
	0x65, 0x74, 0x2e, 0x66, 0x61, 0x75, 0x63, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x16, 0x2e, 0x66, 0x61, 0x75, 0x63, 0x65, 0x74, 0x2e, 0x66, 0x61, 0x75, 0x63, 0x65, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14,
	0x3a, 0x01, 0x2a, 0x22, 0x0f, 0x2f, 0x66, 0x61, 0x75, 0x63, 0x65, 0x74, 0x2f, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x42, 0x19, 0x5a, 0x17, 0x65, 0x74, 0x68, 0x2d, 0x66, 0x61, 0x75, 0x63,
	0x65, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x66, 0x61, 0x75, 0x63, 0x65, 0x74, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_faucet_faucet_proto_rawDescOnce sync.Once
	file_faucet_faucet_proto_rawDescData = file_faucet_faucet_proto_rawDesc
)

func file_faucet_faucet_proto_rawDescGZIP() []byte {
	file_faucet_faucet_proto_rawDescOnce.Do(func() {
		file_faucet_faucet_proto_rawDescData = protoimpl.X.CompressGZIP(file_faucet_faucet_proto_rawDescData)
	})
	return file_faucet_faucet_proto_rawDescData
}

var file_faucet_faucet_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_faucet_faucet_proto_goTypes = []interface{}{
	(*FaucetRequest)(nil),  // 0: faucet.faucetRequest
	(*FaucetResponse)(nil), // 1: faucet.faucetResponse
}
var file_faucet_faucet_proto_depIdxs = []int32{
	0, // 0: faucet.faucet.Request:input_type -> faucet.faucetRequest
	1, // 1: faucet.faucet.Request:output_type -> faucet.faucetResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_faucet_faucet_proto_init() }
func file_faucet_faucet_proto_init() {
	if File_faucet_faucet_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_faucet_faucet_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FaucetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_faucet_faucet_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FaucetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_faucet_faucet_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_faucet_faucet_proto_goTypes,
		DependencyIndexes: file_faucet_faucet_proto_depIdxs,
		MessageInfos:      file_faucet_faucet_proto_msgTypes,
	}.Build()
	File_faucet_faucet_proto = out.File
	file_faucet_faucet_proto_rawDesc = nil
	file_faucet_faucet_proto_goTypes = nil
	file_faucet_faucet_proto_depIdxs = nil
}
